name: BookKeeper CI - My Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build only bookkeeper-server and its dependencies
        run: mvn clean install -DskipTests -pl bookkeeper-server -am

      - name: Run MyProjectTestSuite
        run: mvn -pl bookkeeper-server -Dtest=org.apache.bookkeeper.mytests.MyProjectTestSuite test
